#ifndef dilpostprocess_h__
#define dilpostprocess_h__


struct FingToNtgrNew
{
  char FingType[ARRAY_SIZE];
  char NtgrtypeNew[ARRAY_SIZE];
  int NtgrTypeID;
}Newtypestorage[] = {
//MOBILE 
  {"GENERIC","Network (Generic)",19},
  {"MOBILE","Smart Phone (Generic)",17},
  {"TABLET","Tablet",18},
  {"IPOD","Smart Phone (Generic)",17},
  {"EREADER","Tablet",18},
  {"EBOOK","Tablet",18},
  {"IPAD","Tablet",18},
  {"WATCH","Wearable (Generic)",28},
  {"WEARABLE","Wearable (Generic)",28},
  {"GLASSES","Wearable (Generic)",28},
  {"CAR","IoT (Generic)",11},
//Audio & Video 
  {"MEDIA_PLAYER","Entertainment (Generic)",4},
  {"MEDIAPLAYER","Entertainment (Generic)",4},
  {"MEDIA_SERVER","Entertainment (Generic)",4},
  {"MEDIA","Entertainment (Generic)",4},
  {"TELEVISION","TV",5},
  {"TV","TV",5},
  {"GAME_CONSOLE","Gaming",7},
  {"GAMECONSOLE","Gaming",7},
  {"CONSOLE","Gaming",7},
  {"STREAMING_DONGLE","Media Streamer",6},
  {"STREAMING","Media Streamer",6},
  {"LOUDSPEAKER","Entertainment (Generic)",4},
  {"SOUND_SYSTEM","Entertainment (Generic)",4},
  {"AVRECEIVER","Entertainment (Generic)",4},
  {"STB","Media Streamer",6},
  {"DISC_PLAYER","Entertainment (Generic)",4},
  {"DISCPLAYER","Entertainment (Generic)",4},
  {"SATELLITE","Network (Generic)",19},
  {"MUSIC","Entertainment (Generic)",4},
  {"REMOTE_CONTROL","Entertainment (Generic)",4},
  {"RADIO","Entertainment (Generic)",4},
  {"PHOTO_CAMERA","Camera",25},
  {"CAMERA","Camera",25},
  {"VIDEO_CAMERA","Camera",25},
  {"PHOTOS","Network (Generic)",19},
  {"MICROPHONE","Network (Generic)",19},
  {"PROJECTOR","Entertainment (Generic)",4},
//Home & Office
  {"COMPUTER","Computer (Generic)",1},
  {"LAPTOP","Laptop",2},
  {"DESKTOP","Desktop",3},
  {"PRINTER","Printer",10},
  {"FAX","Printer",10},
  {"PHONE","IP Phone",23},
  {"VOICEMAIL","IP Phone",23},
  {"SCANNER","Home Office (Generic)",9},
  {"POS","Home Office (Generic)",9},
  {"CLOCK","Network (Generic)",19},
  {"BARCODE","Home Office (Generic)",9},
  {"FRAME","Frame",16},
//Smart Home 
  {"SURVEILLANCE_CAMERA","Camera",25},
  {"SURVEILLANCE","Camera",25},
  {"WEBCAM","Camera",25},
  {"SMART_HOME","IoT (Generic)",11},
  {"SMART_PLUG","Smart Plug",12},
  {"WALLPLUG","Smart Plug",12},
  {"LIGHT","Light",14},
  {"VOICE_CONTROL","Smart Speaker",8},
  {"THERMOSTAT","Thermostat",15},
  {"POWER_SYSTEM","IoT (Generic)",11},
  {"SOLAR_PANEL","IoT (Generic)",11},
  {"SMART_METER","IoT (Generic)",11},
  {"ENERGYMETER","IoT (Generic)",11},
  {"HEATING","IoT (Generic)",11},
  {"AIR_CONDITIONER","IoT (Generic)",11},
  {"APPLIANCE","IoT (Generic)",11},
  {"WASHER","IoT (Generic)",11},
  {"FRIDGE","Fridge",13},
  {"CLEANER","IoT (Generic)",11},
  {"SLEEP","IoT (Generic)",11},
  {"GARAGE","IoT (Generic)",11},
  {"SPRINKLER","IoT (Generic)",11},
  {"ELECTRIC","IoT (Generic)",11},
  {"BELL","Doorbell",26},
  {"KEY_LOCK","Smart lock",27},
  {"LOCK","Smart lock",27},
  {"CONTROL_PANEL","IoT (Generic)",11},
  {"SMART_CONTROLLER","IoT (Generic)",11},
  {"SCALE","IoT (Generic)",11},
  {"TOY","IoT (Generic)",11},
  {"ROBOT","IoT (Generic)",11},
  {"WEATHER","IoT (Generic)",11},
  {"HEALTH_MONITOR","Wearable (Generic)",28},
  {"HEALTH","Wearable (Generic)",28},
  {"BABY_MONITOR","Camera",25},
  {"PET_MONITOR","Camera",25},
  {"ALARM","Security (Generic)",24},
  {"MOTION_DETECTOR","Security (Generic)",24},
  {"MOTIONDETECTOR","Security (Generic)",24},
  {"GARAGE","Security (Generic)",24},
  {"SMOKE","Security (Generic)",24},
  {"HUMIDITY","IoT (Generic)",11},
  {"SENSOR","IoT (Generic)",11},
  {"PRESSURE","IoT (Generic)",11},
  {"VOLUME","IoT (Generic)",11},
  {"FINGBOX","Network (Generic)",19},
  {"DOMOTZ_BOX","Network (Generic)",19},
//Network 
  {"ROUTER","Router",21},
  {"WIFI","Network (Generic)",19},
  {"ACCESSPOINT","Network (Generic)",19},
  {"WIFI_EXTENDER","Extender",22},
  {"EXTENDER","Extender",22},
  {"NAS_STORAGE","NAS",20},
  {"HARDDISK","NAS",20},
  {"NASSTORAGE","NAS",20},
  {"RAID","NAS",20},
  {"TAPE","NAS",20},
  {"SAN","NAS",20},
  {"BACKUP","NAS",20},
  {"MODEM","Network (Generic)",19},
  {"SWITCH","Network (Generic)",19},
  {"GATEWAY","Network (Generic)",19},
  {"FIREWALL","Network (Generic)",19},
  {"VPN","Network (Generic)",19},
  {"NASACCESS","Network (Generic)",19},
  {"POE_PLUG","Network (Generic)",19},
  {"ETHERNETPLUG","Network (Generic)",19},
  {"USB","Network (Generic)",19},
  {"SMALL_CELL","Network (Generic)",19},
  {"SMALLCELL","Network (Generic)",19},
  {"CLOUD","Network (Generic)",19},
  {"BATTERY","Network (Generic)",19},
  {"NETWORK_APPLIANCE","Network (Generic)",19},
//Server
  {"VIRTUAL_MACHINE","Computer (Generic)",1},
  {"SERVER","Computer (Generic)",1},
  {"TERMINAL","Computer (Generic)",1},
  {"MAIL_SERVER","Computer (Generic)",1},
  {"MAIL","Computer (Generic)",1},
  {"INBOX","Computer (Generic)",1},
  {"IMAC","Computer (Generic)",1},
  {"EMAIL","Computer (Generic)",1},
  {"FILE_SERVER","Computer (Generic)",1},
  {"PROXY_SERVER","Computer (Generic)",1},
  {"WEB_SERVER","Computer (Generic)",1},
  {"DOMAIN_SERVER","Computer (Generic)",1},
  {"COMMUNICATION","Computer (Generic)",1},
  {"DATABASE","Computer (Generic)",1},
//Engineering
  {"RASPBERRY","Network (Generic)",19},
  {"ARDUINO","Network (Generic)",19},
  {"PROCESSOR","Network (Generic)",19},
  {"CIRCUIT_CARD","Network (Generic)",19},
  {"EXPANSION_CARD","Network (Generic)",19},
  {"RFID","Network (Generic)",19},
};

#define MAX_ENTRY sizeof(Newtypestorage)/sizeof(Newtypestorage[0])
#define MAX_DEVICE_TYPE_ID 28
#endif  // dilpostprocess_h_
