
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[668] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  103,  102,
       92,   93,  102,   94,   97,  101,  101,   96,   95,   98,
       99,  100,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,    2,
        2,    2,    4,    4,    4,   95,  101,  101,   46,  101,
      101,   47,   70,   70,   70,   83,   83,   83,  102,    6,
        6,    6,  102,  101,   52,   92,    0,   91,   94,  101,
       95,  101,   95,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,   17,  101,    2,    2,    2,
        2,    4,    4,    4,    4,    8,    8,   46,  101,   46,
       45,   44,   70,   70,   70,   70,   83,   83,   83,   83,
        0,   87,    6,    6,    6,    6,    0,   90,   52,  101,
       52,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       74,  101,  101,  101,  101,   58,   55,  101,  101,  101,
      101,  101,   73,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,    7,  101,  101,
        3,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,    5,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   15,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   42,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   22,   21,  101,  101,  101,  101,  101,
       85,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   16,  101,   84,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,    8,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   61,  101,  101,  101,   88,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   19,  101,   10,  101,  101,  101,  101,  101,  101,
       12,   86,  101,  101,   49,  101,  101,  101,  101,  101,
       80,    9,  101,  101,  101,  101,  101,   75,  101,  101,
      101,  101,  101,  101,  101,   79,  101,   89,  101,  101,
      101,   82,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,   14,  101,  101,   50,

      101,  101,  101,  101,   78,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   77,   43,
       68,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   71,  101,   76,  101,  101,  101,  101,
      101,  101,  101,  101,  101,   72,  101,  101,  101,  101,
      101,   64,   62,  101,   63,  101,  101,  101,    1,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   56,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   13,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,   11,  101,  101,  101,  101,

      101,  101,   36,  101,  101,  101,  101,  101,  101,  101,
       60,   66,  101,  101,   24,  101,   81,  101,  101,  101,
      101,   27,  101,  101,  101,  101,   34,  101,   37,  101,
      101,  101,   18,  101,  101,  101,   67,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   57,   20,  101,
      101,  101,   51,  101,  101,  101,   59,   65,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   69,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   38,  101,
      101,  101,  101,  101,  101,   29,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,   54,  101,  101,  101,
       41,  101,  101,   31,  101,  101,  101,   48,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   53,  101,  101,  101,   28,  101,  101,  101,  101,
       25,  101,  101,  101,   23,  101,   30,  101,   35,  101,
       32,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       39,  101,   26,  101,   40,   33,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   11,   10,   10,   10,   10,   12,   13,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   15,   15,
       18,   19,   18,   18,   18,   18,   20,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   18,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   18,   46,    1,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[48] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[684] =
    {   0,
        0,   47,   76,    0,  118,  165,    0,    0,  212,  259,
      297,    0,    8,   25,  324,  371,  418,  465,  927,  926,
      512,  559,  925,  924,    4,   12,    0,    0,  927,  932,
      924,  932,  921,    0,  932,    0,   14,  932,   18,  932,
      932,  932,  904,    2,  899,  890,    4,  877,    5,   40,
      894,  884,    1,   28,   32,   50,   53,  883,  891,    0,
       70,   76,    0,   79,  122,  599,  126,   81,  130,  894,
      890,  932,    0,   86,  134,    0,   93,  138,  910,    0,
      140,  144,  909,  146,  150,  910,  907,  932,    0,    0,
      152,  169,  173,  896,  884,   50,  868,  874,  885,   31,

      872,  874,  867,  880,  862,  893,  892,  158,  853,  863,
      857,  859,  854,  858,  862,  856,   82,  152,  857,  165,
      851,  101,  852,  865,  854,    0,  851,    0,  180,  183,
      189,    0,  185,  193,  197,  216,  872,  199,  219,  223,
        0,    0,    0,  225,  227,  231,    0,  233,  235,  239,
      879,  932,    0,  241,  243,  263,  878,  932,  245,  265,
      269,  865,  842,  844,  843,  848,  852,  256,  853,  853,
      851,  847,  841,  846,  829,  249,  846,  835,    2,  840,
      835,  829,  136,  856,  259,    0,    0,  830,  834,  253,
      832,  829,    0,  826,  822,  818,  814,  824,  815,  827,

      821,  843,  842,  841,  822,  617,  199,  820,  807,  801,
      817,  803,  815,  816,  794,  261,  808,    0,  799,  284,
        0,  814,  810,  795,  792,  798,  793,  792,  223,  805,
      262,  821,  788,  784,  790,    0,  262,  783,  788,  796,
      796,  787,  785,  792,  791,  780,  789,    0,  792,  774,
      265,  199,  777,  635,  791,  793,  770,  778,    0,  773,
      799,  763,  771,  777,  770,  758,  765,  275,  773,  764,
      771,  763,  770,    0,    0,  755,  768,  762,  758,  763,
        0,  762,  753,  752,  760,  271,  759,  758,  749,  744,
      737,  756,  755,    0,  771,    0,  750,  737,  736,  734,

      733,  740,  745,  745,  743,  746,  728,  728,  753,  747,
      752,  723,  721,  720,  720,  728,  731,  731,  713,  712,
      728,    0,  710,  717,  743,    0,  724,  737,  712,  720,
      705,  722,  721,  707,  700,  707,  701,  703,  711,  698,
      701,    0,  708,  726,  692,  696,  706,  699,  699,  687,
        0,    0,  692,  687,    0,  690,  295,  697,  715,  710,
        0,  713,  690,  688,  691,  692,  676,  683,  687,  686,
      685,  684,  684,  674,  696,    0,  682,    0,  660,  664,
      679,    0,  668,  679,  658,  666,  660,  655,  671,  661,
      664,  669,  653,  621,  627,  614,    0,  612,  606,    0,

      640,  631,  599,  312,    0,  600,  602,  606,  591,  594,
      597,  592,  579,  574,  579,  570,  569,  581,    0,    0,
        0,  572,  575,  560,  569,  572,  575,  554,  569,  559,
      569,  558,  559,    0,  557,    0,  559,  555,  561,  553,
      547,  577,  551,  546,  546,    0,  558,  537,  538,  550,
      531,    0,    0,  545,    0,  536,  540,  536,    0,  540,
      523,  518,  525,  528,  515,  514,  525,  510,  527,  515,
      514,    0,  508,  515,  504,  519,  520,  515,  505,  499,
      512,  492,  510,    0,  510,  269,  508,  499,  494,  524,
      523,  495,  490,  488,  519,    0,  498,  480,  480,  483,

      501,  473,    0,  474,  466,  480,  471,  472,  463,  464,
        0,    0,  474,  457,  490,  489,    0,  461,  316,  487,
      486,    0,  453,  453,  451,  449,    0,  318,    0,  466,
      448,  456,    0,  450,  477,  457,    0,  452,  442,  445,
      457,  452,  437,  429,  320,  426,  434,    0,    0,  435,
      424,  419,  450,  429,  421,  322,    0,    0,  428,  419,
      419,  426,  417,  427,  423,  412,  420,  423,  419,  410,
      403,  416,  410,    0,  414,  403,  399,  404,  409,  396,
      411,  399,  405,  392,  392,  391,  376,  391,    0,  390,
      387,  385,  376,  366,  362,    0,  380,  375,  378,  365,

      380,  371,  374,  373,  368,  357,    0,  358,  373,  368,
        0,  354,  358,    0,  365,  360,  362,    0,  349,  353,
      364,  359,  353,  340,  330,  361,  328,  332,  335,  325,
      356,    0,  323,  327,  321,    0,  325,  319,  350,  332,
        0,  321,  315,  346,    0,  330,    0,  316,    0,  327,
        0,  314,  313,  294,  282,  280,  272,  253,  175,  144,
        0,  133,    0,  127,    0,    0,  932,  662,  665,  668,
      671,  674,  677,  680,  683,  144,  110,   65,   18,   14,
      686,    4,  689
    } ;

static yyconst flex_int16_t yy_def[684] =
    {   0,
      668,  668,    2,    3,  669,  669,    2,    2,  670,  670,
        2,   11,    2,    2,  671,  671,  672,  672,    2,    2,
      673,  673,    2,    2,    2,    2,    2,    2,  667,  667,
      667,  667,  674,  675,  667,  676,  676,  667,  676,  667,
      667,  667,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  677,
      677,  677,  678,  678,  678,  676,   66,  676,  676,  676,
      676,  667,  679,  679,  679,  680,  680,  680,  681,  682,
      682,  682,  683,  676,  676,  667,  674,  667,  675,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  677,  677,  677,
      677,  678,  678,  678,  678,  676,  676,  676,  676,  676,
      676,  676,  679,  679,  679,  679,  680,  680,  680,  680,
      681,  667,  682,  682,  682,  682,  683,  667,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,

      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,  676,  676,  676,  676,
      676,  676,  676,  676,  676,  676,    0,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667
    } ;

static yyconst flex_uint16_t yy_nxt[980] =
    {   0,
       30,   31,   32,   33,   34,   35,  153,   37,   38,   39,
       39,   84,   40,   85,   85,   68,  147,   69,   69,   84,
      143,   85,   85,   91,   91,   92,   95,   93,   93,  100,
      111,  226,   68,   96,   69,   69,  227,  104,  101,  105,
      112,   70,   97,   71,  102,   41,   42,   30,   31,   32,
       33,   34,   35,   72,   37,   38,   39,   39,   70,   40,
       71,  106,  169,  113,  107,  114,  116,  132,  115,  117,
       72,  118,  170,  108,  119,  120,  121,  164,  122,  129,
      129,  165,  123,  130,  124,  131,  131,  125,  133,  133,
      138,  138,   41,   42,   43,  144,  144,   44,   45,   46,

       47,   48,  148,  148,   49,   50,   51,  189,   52,   53,
       54,   55,  128,   56,   57,   58,  190,   59,   30,   31,
       32,   33,   34,   35,  199,   61,   38,   62,   62,  134,
       40,  135,  135,   90,  200,  137,  137,  139,  201,  140,
      140,  145,  231,  146,  146,  149,   90,  150,  150,  154,
      154,  155,  666,  156,  156,  159,  159,  160,  665,  161,
      161,   91,   91,   41,   42,   30,   31,   32,   33,   34,
       35,  232,   61,   38,   62,   62,  664,   40,   91,   91,
       92,  178,   93,   93,  179,  191,  194,  192,  195,  129,
      129,  196,  129,  129,  133,  133,  130,  180,  131,  131,

      663,  197,  133,  133,  134,  255,  135,  135,  138,  138,
       41,   42,   30,   31,   32,   33,   34,   35,  256,   64,
       38,   65,   65,   92,   40,   93,   93,  206,  138,  138,
      139,  306,  140,  140,  144,  144,  144,  144,  145,  307,
      146,  146,  148,  148,  148,  148,  149,  281,  150,  150,
      154,  154,  154,  154,  159,  159,  282,   41,   42,   30,
       31,   32,   33,   34,   35,  234,   64,   38,   65,   65,
      155,   40,  156,  156,  159,  159,  160,  238,  161,  161,
      213,  214,  222,  265,  223,  662,  284,  290,  235,  266,
      272,  291,  239,  267,  304,  338,  305,  661,  513,  268,

      285,  660,  269,  514,   41,   42,   66,   66,  322,  339,
       67,   67,   67,   67,  659,  658,  273,  323,   67,   67,
       67,   67,   67,   67,   30,   31,   32,   33,   34,   35,
      401,   74,   38,   75,   75,  443,   40,  542,  402,  550,
      543,  565,  551,  575,  566,  657,  576,  656,  655,  654,
      444,  653,  652,  651,  650,  649,  648,  647,  646,  645,
      644,  643,  642,  641,  640,  639,  638,  637,  636,   41,
       42,   30,   31,   32,   33,   34,   35,  635,   74,   38,
       75,   75,  634,   40,  633,  632,  631,  630,  629,  628,
      627,  626,  625,  624,  623,  622,  621,  620,  619,  618,

      617,  616,  615,  614,  613,  612,  611,  610,  609,  608,
      607,  606,  605,  604,  603,  602,   41,   42,   30,   31,
       32,   33,   34,   35,  601,   77,   38,   78,   78,  600,
       40,  599,  598,  597,  596,  595,  594,  593,  592,  591,
      590,  589,  588,  587,  586,  585,  584,  583,  582,  581,
      580,  579,  578,  577,  574,  573,  572,  571,  570,  569,
      568,  567,  564,   41,   42,   30,   31,   32,   33,   34,
       35,  563,   77,   38,   78,   78,  562,   40,  561,  560,
      559,  558,  557,  556,  555,  554,  553,  552,  549,  548,
      547,  546,  545,  544,  541,  540,  539,  538,  537,  536,

      535,  534,  533,  532,  531,  530,  529,  528,  527,  526,
       41,   42,   30,   31,   32,   33,   34,   35,  525,   81,
       38,   82,   82,  524,   40,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,   41,   42,   30,
       31,   32,   33,   34,   35,  489,   81,   38,   82,   82,
      488,   40,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,

      459,  458,  457,  456,   41,   42,   92,  455,  136,  136,
      454,  453,  137,  137,  137,  137,  452,  451,  450,  449,
      137,  137,  137,  137,  137,  137,  254,  254,  448,  447,
      254,  254,  254,  254,  446,  445,  442,  441,  254,  254,
      254,  254,  254,  254,  309,  309,  440,  439,  309,  309,
      309,  309,  438,  437,  436,  435,  309,  309,  309,  309,
      309,  309,   36,   36,   36,   60,   60,   60,   63,   63,
       63,   73,   73,   73,   76,   76,   76,   80,   80,   80,
       87,   87,   87,   89,  434,   89,  151,  151,  151,  157,
      157,  157,  433,  432,  431,  430,  429,  428,  427,  426,

      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  206,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  321,

      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  308,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  289,  288,  287,  286,  283,  280,
      279,  278,  277,  276,  275,  274,  271,  270,  264,  263,
      262,  261,  260,  259,  258,  257,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      237,  236,  233,  230,  229,  228,  225,  224,  221,  220,
      219,  218,  217,  216,  215,  212,  211,  210,  209,  208,
      207,  158,  152,  206,  205,  204,  203,  202,  198,  193,
      188,  187,  186,  185,  184,  183,  182,  181,  177,  176,

      175,  174,  173,  172,  171,  168,  167,  166,  163,  162,
       88,   86,  158,  152,  142,  141,  127,  126,  110,  109,
      103,   99,   98,   94,   88,   86,  667,   83,   83,   79,
       79,   29,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667
    } ;

static yyconst flex_int16_t yy_chk[980] =
    {   0,
        1,    1,    1,    1,    1,    1,  682,    1,    1,    1,
        1,   25,    1,   25,   25,   13,  680,   13,   13,   26,
      679,   26,   26,   37,   37,   39,   44,   39,   39,   47,
       53,  179,   14,   44,   14,   14,  179,   49,   47,   49,
       53,   13,   44,   13,   47,    1,    1,    2,    2,    2,
        2,    2,    2,   13,    2,    2,    2,    2,   14,    2,
       14,   50,  100,   54,   50,   54,   55,  678,   54,   55,
       14,   56,  100,   50,   56,   56,   57,   96,   57,   61,
       61,   96,   57,   62,   57,   62,   62,   57,   64,   64,
       68,   68,    2,    2,    3,   74,   74,    3,    3,    3,

        3,    3,   77,   77,    3,    3,    3,  117,    3,    3,
        3,    3,  677,    3,    3,    3,  117,    3,    5,    5,
        5,    5,    5,    5,  122,    5,    5,    5,    5,   65,
        5,   65,   65,   67,  122,   67,   67,   69,  122,   69,
       69,   75,  183,   75,   75,   78,  676,   78,   78,   81,
       81,   82,  664,   82,   82,   84,   84,   85,  662,   85,
       85,   91,   91,    5,    5,    6,    6,    6,    6,    6,
        6,  183,    6,    6,    6,    6,  660,    6,   92,   92,
       93,  108,   93,   93,  108,  118,  120,  118,  120,  129,
      129,  120,  130,  130,  133,  133,  131,  108,  131,  131,

      659,  120,  134,  134,  135,  207,  135,  135,  138,  138,
        6,    6,    9,    9,    9,    9,    9,    9,  207,    9,
        9,    9,    9,  136,    9,  136,  136,  136,  139,  139,
      140,  252,  140,  140,  144,  144,  145,  145,  146,  252,
      146,  146,  148,  148,  149,  149,  150,  229,  150,  150,
      154,  154,  155,  155,  159,  159,  229,    9,    9,   10,
       10,   10,   10,   10,   10,  185,   10,   10,   10,   10,
      156,   10,  156,  156,  160,  160,  161,  190,  161,  161,
      168,  168,  176,  216,  176,  658,  231,  237,  185,  216,
      220,  237,  190,  216,  251,  286,  251,  657,  486,  216,

      231,  656,  216,  486,   10,   10,   11,   11,  268,  286,
       11,   11,   11,   11,  655,  654,  220,  268,   11,   11,
       11,   11,   11,   11,   15,   15,   15,   15,   15,   15,
      357,   15,   15,   15,   15,  404,   15,  519,  357,  528,
      519,  545,  528,  556,  545,  653,  556,  652,  650,  648,
      404,  646,  644,  643,  642,  640,  639,  638,  637,  635,
      634,  633,  631,  630,  629,  628,  627,  626,  625,   15,
       15,   16,   16,   16,   16,   16,   16,  624,   16,   16,
       16,   16,  623,   16,  622,  621,  620,  619,  617,  616,
      615,  613,  612,  610,  609,  608,  606,  605,  604,  603,

      602,  601,  600,  599,  598,  597,  595,  594,  593,  592,
      591,  590,  588,  587,  586,  585,   16,   16,   17,   17,
       17,   17,   17,   17,  584,   17,   17,   17,   17,  583,
       17,  582,  581,  580,  579,  578,  577,  576,  575,  573,
      572,  571,  570,  569,  568,  567,  566,  565,  564,  563,
      562,  561,  560,  559,  555,  554,  553,  552,  551,  550,
      547,  546,  544,   17,   17,   18,   18,   18,   18,   18,
       18,  543,   18,   18,   18,   18,  542,   18,  541,  540,
      539,  538,  536,  535,  534,  532,  531,  530,  526,  525,
      524,  523,  521,  520,  518,  516,  515,  514,  513,  510,

      509,  508,  507,  506,  505,  504,  502,  501,  500,  499,
       18,   18,   21,   21,   21,   21,   21,   21,  498,   21,
       21,   21,   21,  497,   21,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  485,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,   21,   21,   22,
       22,   22,   22,   22,   22,  460,   22,   22,   22,   22,
      458,   22,  457,  456,  454,  451,  450,  449,  448,  447,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  435,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  424,

      423,  422,  418,  417,   22,   22,   66,  416,   66,   66,
      415,  414,   66,   66,   66,   66,  413,  412,  411,  410,
       66,   66,   66,   66,   66,   66,  206,  206,  409,  408,
      206,  206,  206,  206,  407,  406,  403,  402,  206,  206,
      206,  206,  206,  206,  254,  254,  401,  399,  254,  254,
      254,  254,  398,  396,  395,  394,  254,  254,  254,  254,
      254,  254,  668,  668,  668,  669,  669,  669,  670,  670,
      670,  671,  671,  671,  672,  672,  672,  673,  673,  673,
      674,  674,  674,  675,  393,  675,  681,  681,  681,  683,
      683,  683,  392,  391,  390,  389,  388,  387,  386,  385,

      384,  383,  381,  380,  379,  377,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      360,  359,  358,  356,  354,  353,  350,  349,  348,  347,
      346,  345,  344,  343,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  325,
      324,  323,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  295,  293,  292,
      291,  290,  289,  288,  287,  285,  284,  283,  282,  280,
      279,  278,  277,  276,  273,  272,  271,  270,  269,  267,

      266,  265,  264,  263,  262,  261,  260,  258,  257,  256,
      255,  253,  250,  249,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  235,  234,  233,  232,  230,  228,
      227,  226,  225,  224,  223,  222,  219,  217,  215,  214,
      213,  212,  211,  210,  209,  208,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  192,  191,
      189,  188,  184,  182,  181,  180,  178,  177,  175,  174,
      173,  172,  171,  170,  169,  167,  166,  165,  164,  163,
      162,  157,  151,  137,  127,  125,  124,  123,  121,  119,
      116,  115,  114,  113,  112,  111,  110,  109,  107,  106,

      105,  104,  103,  102,  101,   99,   98,   97,   95,   94,
       87,   86,   83,   79,   71,   70,   59,   58,   52,   51,
       48,   46,   45,   43,   33,   31,   29,   24,   23,   20,
       19,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cftoken.l"
/*	$KAME: cftoken.l,v 1.35 2005/01/12 06:06:11 suz Exp $	*/
#line 4 "cftoken.l"
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <sys/time.h>

#include <netinet/in.h>

#include <errno.h>
#include <syslog.h>
#include <string.h>
#ifdef HAVE_STDARG_H
#include <stdarg.h>
#else
#include <varargs.h>
#endif

#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include "y.tab.h"

#define YY_NO_UNPUT 1

char *configfilename;
int lineno = 1;


/* Recursion limit for includes */
#define MAX_INCLUDE_DEPTH 10

static struct include_stack {
	char *path;
	YY_BUFFER_STATE state;
	int lineno;
} incstack[MAX_INCLUDE_DEPTH];
int incstackp = 0;


static int yy_first_time = 1;
static int yyerrorcount = 0;

#ifndef NOCONFIG_DEBUG
#define YYDEBUG 1

int cfdebug = 1;
#else
int cfdebug = 0;
#endif

extern int yyparse __P((void));
extern int cf_post_config __P((void));

static void cfdebug_print __P((char *, char *, int));

#define DP(str) if (cfdebug) cfdebug_print(str, yytext, yyleng)
#define DECHO if (cfdebug) cfdebug_print(NULL, yytext, yyleng);
#define DNOECHO if (cfdebug) cfdebug_print(NULL, "****", yyleng);
/* abbreviations */













#line 1003 "lex.yy.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_PREF 3
#define S_HOST 4
#define S_DUID 5
#define S_IA 6
#define S_AUTH 7
#define S_KEY 8
#define S_SECRET 9
#define S_ADDRPOOL 10
#define S_INCL 11
#define S_VENDOR_CLASS 12
#define S_VENDOR 13

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 126 "cftoken.l"


	if (yy_first_time) {
		BEGIN S_CNF;
		yy_first_time = 0;
	}

	/* interface configuration */
#line 1243 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 668 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 932 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 134 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 135 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
/* host configuration */
case 3:
YY_RULE_SETUP
#line 143 "cftoken.l"
{ DECHO; BEGIN S_HOST; return (HOST); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 144 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (HOSTNAME);
}
	YY_BREAK
/* address pool configuration */
case 5:
YY_RULE_SETUP
#line 152 "cftoken.l"
{ DECHO; BEGIN S_ADDRPOOL; return (ADDRPOOL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 154 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (POOLNAME);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 161 "cftoken.l"
{ DECHO; BEGIN S_DUID; return (DUID); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 162 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (DUID_ID);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 169 "cftoken.l"
{ DECHO; return (ADDRESS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 171 "cftoken.l"
{ DECHO; return (PREFIX); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 173 "cftoken.l"
{ DECHO; return (PREFERENCE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 175 "cftoken.l"
{ DECHO; return (SCRIPT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 177 "cftoken.l"
{ DECHO; return (DELAYEDKEY); }
	YY_BREAK
/* request */
case 14:
YY_RULE_SETUP
#line 180 "cftoken.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 15:
YY_RULE_SETUP
#line 183 "cftoken.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* range */
case 16:
YY_RULE_SETUP
#line 186 "cftoken.l"
{ DECHO; return (RANGE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 187 "cftoken.l"
{ DECHO; return (TO); }
	YY_BREAK
/* address-pool */
case 18:
YY_RULE_SETUP
#line 190 "cftoken.l"
{ DECHO; return (ADDRESS_POOL); }
	YY_BREAK
/* DHCP options */
case 19:
YY_RULE_SETUP
#line 193 "cftoken.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "cftoken.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 196 "cftoken.l"
{ DECHO; return (IA_PD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 197 "cftoken.l"
{ DECHO; return (IA_NA); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 198 "cftoken.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 199 "cftoken.l"
{ DECHO; return (DNS_NAME); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 200 "cftoken.l"
{ DECHO; return (SIP_SERVERS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 201 "cftoken.l"
{ DECHO; return (SIP_NAME); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 202 "cftoken.l"
{ DECHO; return (NTP_SERVERS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 203 "cftoken.l"
{ DECHO; return (NIS_SERVERS); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 204 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 205 "cftoken.l"
{ DECHO; return (NISP_SERVERS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 206 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 207 "cftoken.l"
{ DECHO; return (BCMCS_SERVERS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 208 "cftoken.l"
{ DECHO; return (BCMCS_NAME); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 209 "cftoken.l"
{ DECHO; return (REFRESHTIME); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 210 "cftoken.l"
{ DECHO; return (OPT_VENDOR_SPEC); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 211 "cftoken.l"
{ DECHO; return (SOLMAXRT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 212 "cftoken.l"
{ DECHO; return (SOLMAPMIN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 213 "cftoken.l"
{ DECHO; return (SOLUSERCLASS); }
	YY_BREAK
/* provided for a backward compatibility to WIDE-DHCPv6 before Oct 1 2006 */
case 39:
YY_RULE_SETUP
#line 216 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 217 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
/* generic options */
case 41:
YY_RULE_SETUP
#line 220 "cftoken.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 222 "cftoken.l"
{ DECHO; return (ALLOW); }
	YY_BREAK
/* identity association */
case 43:
YY_RULE_SETUP
#line 225 "cftoken.l"
{ DECHO; BEGIN S_IA; return(ID_ASSOC); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 226 "cftoken.l"
{ DECHO; return(IA_PD); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 227 "cftoken.l"
{ DECHO; return(IA_NA); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 228 "cftoken.l"
{ DECHO; yylval.str = strdup(yytext); return(IAID); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 229 "cftoken.l"
{ DP("begin of closure"); BEGIN S_CNF; return (BCL); }
	YY_BREAK
/*
	 * interface parameters for delegated prefix configuration.
	 * when lex reads an interface name, the state will be back to
	 * S_CNF.
	 */
case 48:
YY_RULE_SETUP
#line 236 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (PREFIX_INTERFACE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 237 "cftoken.l"
{ DECHO; return (SLA_ID); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 238 "cftoken.l"
{ DECHO; return (SLA_LEN); }
	YY_BREAK
/* Vendor-class Option */
case 51:
YY_RULE_SETUP
#line 241 "cftoken.l"
{ DECHO; BEGIN S_VENDOR_CLASS; return(VENDOR_CLASS); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 242 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return(VENDOR_CLASS_IANA);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 249 "cftoken.l"
{ DECHO; return (VENDOR_CLASS_DATA); }
	YY_BREAK
/* Vendor-specific Information Option */
case 54:
YY_RULE_SETUP
#line 252 "cftoken.l"
{ DECHO; BEGIN S_CNF; return (VENDOR_SPEC); }
	YY_BREAK
/* Vendor-specific Information suboptions for Enterprise ID: The Broadband Forum(3561) */
case 55:
YY_RULE_SETUP
#line 255 "cftoken.l"
{ DECHO; return (VENDOR_OUI); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 256 "cftoken.l"
{ DECHO; return (VENDOR_SN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 257 "cftoken.l"
{ DECHO; return (VENDOR_PD); }
	YY_BREAK
/* Vendor-specific Information suboptions for Enterprise ID: Charter Communications(9914) */
case 58:
YY_RULE_SETUP
#line 260 "cftoken.l"
{ DECHO; return (VENDOR_ORO); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 261 "cftoken.l"
{ DECHO; return (VENDOR_DEVTYPE); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 262 "cftoken.l"
{ DECHO; return (VENDOR_ECMESAFE); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 263 "cftoken.l"
{ DECHO; return (VENDOR_DEVSN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 264 "cftoken.l"
{ DECHO; return (VENDOR_DEVHWVER); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 265 "cftoken.l"
{ DECHO; return (VENDOR_DEVSWVER); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 266 "cftoken.l"
{ DECHO; return (VENDOR_DEVBLVER); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 267 "cftoken.l"
{ DECHO; return (VENDOR_DEVVENDEROUI); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 268 "cftoken.l"
{ DECHO; return (VENDOR_DEVMODELID); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 269 "cftoken.l"
{ DECHO; return (VENDOR_DEVVENDERID); }
	YY_BREAK
/* duration */
case 68:
YY_RULE_SETUP
#line 272 "cftoken.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* authentication option */
case 69:
YY_RULE_SETUP
#line 275 "cftoken.l"
{ DECHO; BEGIN S_AUTH; return (AUTHENTICATION); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 276 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (AUTHNAME);
}
	YY_BREAK
/* authentication parameters */
case 71:
YY_RULE_SETUP
#line 284 "cftoken.l"
{ DECHO; return (PROTOCOL); };
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 285 "cftoken.l"
{ DECHO; return (ALGORITHM); };
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 286 "cftoken.l"
{ DECHO; return (RDM); };
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 287 "cftoken.l"
{ DECHO; return (KEY); };
	YY_BREAK
/* authentication protocols */
case 75:
YY_RULE_SETUP
#line 290 "cftoken.l"
{ DECHO; return (DELAYED); };
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 291 "cftoken.l"
{ DECHO; return (RECONFIG); };
	YY_BREAK
/* authentication algorithms */
case 77:
YY_RULE_SETUP
#line 294 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 295 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 296 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 297 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
/* authentication RDM */
case 81:
YY_RULE_SETUP
#line 300 "cftoken.l"
{ DECHO; return (MONOCOUNTER); };
	YY_BREAK
/* secret keys */
case 82:
YY_RULE_SETUP
#line 303 "cftoken.l"
{ DECHO; BEGIN S_KEY; return (KEYINFO); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 304 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (KEYNAME);
}
	YY_BREAK
/* key parameters */
case 84:
YY_RULE_SETUP
#line 312 "cftoken.l"
{ DECHO; return (REALM); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 313 "cftoken.l"
{ DECHO; return (KEYID); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 314 "cftoken.l"
{ DECHO; BEGIN S_SECRET; return (SECRET); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 315 "cftoken.l"
{
	DNOECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 321 "cftoken.l"
{ DECHO; return (EXPIRE); }
	YY_BREAK
/* include */
case 89:
YY_RULE_SETUP
#line 324 "cftoken.l"
{ DECHO; BEGIN S_INCL; return (INCLUDE); }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 325 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
/* quoted string */
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 333 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (QSTRING);
	}
	YY_BREAK
/* misc */
case 92:
YY_RULE_SETUP
#line 340 "cftoken.l"
{ ; }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 341 "cftoken.l"
{ lineno++; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 342 "cftoken.l"
{ DP("comment"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 343 "cftoken.l"
{
	DECHO;
	yylval.num = strtoll(yytext, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 348 "cftoken.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 349 "cftoken.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 350 "cftoken.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 351 "cftoken.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 352 "cftoken.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 101:
YY_RULE_SETUP
#line 355 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (STRING);
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_PREF):
case YY_STATE_EOF(S_HOST):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_IA):
case YY_STATE_EOF(S_AUTH):
case YY_STATE_EOF(S_KEY):
case YY_STATE_EOF(S_SECRET):
case YY_STATE_EOF(S_ADDRPOOL):
case YY_STATE_EOF(S_INCL):
case YY_STATE_EOF(S_VENDOR_CLASS):
case YY_STATE_EOF(S_VENDOR):
#line 361 "cftoken.l"
{
		if (--incstackp < 0)
			yyterminate();
		else {
			yy_delete_buffer(YY_CURRENT_BUFFER);
			free(incstack[incstackp + 1].path);
			configfilename = incstack[incstackp].path;
			lineno = incstack[incstackp].lineno;
			yy_switch_to_buffer(incstack[incstackp].state);
		}
	}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 373 "cftoken.l"
ECHO;
	YY_BREAK
#line 1929 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 668 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 668 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 667);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 373 "cftoken.l"


static void
cfdebug_print(w, t, l)
	char *w, *t;
	int l;
{
	if (w) {
		dprintf(LOG_DEBUG, FNAME,
		    "<%d>%s [%s] (%d)", yy_start, w, t, l);
	} else {
		dprintf(LOG_DEBUG, FNAME,
		    "<%d>[%s] (%d)", yy_start, t, l);
	}
}

static void
yyerror0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dprintf(level, FNAME, ebuf);
}

void
yyerror(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_ERR, s, ap);
	va_end(ap);
	yyerrorcount++;
}

void
yywarn(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfswitch_buffer(incl)
	char *incl;
{
	char *path = qstrdup(incl);
	FILE *fp;

	if (incstackp >= MAX_INCLUDE_DEPTH) {
		dprintf(LOG_ERR, FNAME, "cfparse: includes nested too deeply");
		return (-1);
	}
	incstack[incstackp].path = configfilename;
	incstack[incstackp].state = YY_CURRENT_BUFFER;
	incstack[incstackp].lineno = lineno;

	fp = fopen(path, "r");
	if (fp == NULL) {
		dprintf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			path, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}
	incstackp++;
	configfilename = path;
	lineno = 1;
	yy_switch_to_buffer(yy_create_buffer(fp,YY_BUF_SIZE));

	BEGIN(S_CNF);

	return (0);
}

int
cfparse(conf)
	char *conf;
{
	configfilename = conf;
	if ((yyin = fopen(configfilename, "r")) == NULL) {
		dprintf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}

	if (yyparse() || yyerrorcount) {
		if (yyerrorcount) {
			yyerror("fatal parse failure: exiting (%d errors)",
				yyerrorcount);
		} else
			yyerror("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

