#!/bin/sh /etc/rc.common
# workaround to disable ecm if blocksite enabled
# 54: need to disable before hyd(55)

START=54

bs_enable="$(nvram get bs_enable)"  

start() {
    if [ "$bs_enable" != "0" ]; then
        echo "===S54stop_ecm, stop ecm and sfe done===" > /dev/console
        /etc/init.d/qca-nss-ecm stop
        /etc/init.d/shortcut-fe disable
        /etc/init.d/qca-nss-ecm disable
        return 1
    fi
    /etc/init.d/shortcut-fe enable
    /etc/init.d/qca-nss-ecm enable
    echo "===S54stop_ecm start ecm and sfe done===" > /dev/console 
}
